name: TEST-MASTER

on:
  push:
    branches: master
  # workflow_dispatch: # optional manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6  # specify your version

      # Run terraform fmt to auto-format code
      - name: Terraform Format
        run: terraform fmt -recursive

      # (Optional) Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate
